### ISSUE TITLE
Could add a boilerplate of nextjs?

### ISSUE THREAD

**Issue by zwl1619** [hammerframework/hammer#11]
Could add a boilerplate of nextjs?

**Comment by mojombo** [comment]
I’m not sure what you’re requesting. Can you elaborate?

**Comment by zwl1619** [comment]
I mean, could add some sample like [hasura](https://github.com/hasura/graphql-engine)? 
Not as many as it，focus on react，such as nextjs.

https://github.com/hasura/graphql-engine/tree/master/community/sample-apps

**Comment by mojombo** [comment]
We do have three example projects, listed at the top of the Readme. We will be adding more examples and full documentation as Hammer matures!
